export const routesUser = {
  home: "/",
  ordersList: "/orders-list",
  history: "/history",
  historyPoint: "/history-point",
  orderDetail: "/orders-list/:orderId",
  productType: "/product-type/:productTypeId",
  giftsList: "/gifts-list",
  giftDetail: "/gifts-list/:giftId",
  vouchersList: "/vouchers-list",
  voucherDetail: "/vouchers-list/:voucherId",
  profile: "/profile",
  cart: "/cart",
  information: "/information",
  addressesManager: "/addresses-manager",
  introduce: "/introduce",
  tablePriceTour: "/price-tour",
  contact: "/contact",
  booking: "/booking/:id",
  tour: "/tour",
  tourOfList: "/tour/:id",
  tourDetail: "/tour-detail/:id",
  blogs: "/blog",
  picturePage: "/picture-page",
  blogDetail: "/blog-detail/:id",
};
